# Generated by Django 4.2 on 2023-04-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myForum', '0002_alter_topic_author_alter_topic_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='content',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/'),
        ),
    ]
