# Generated by Django 4.2 on 2023-04-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myForum', '0003_topic_content_topic_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic_link',
            field=models.CharField(blank=True, null=True),
        ),
    ]
